// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPages.Data;

#nullable disable

namespace RazorPages.Data.Migrations
{
    [DbContext(typeof(RazorPagesContext))]
    [Migration("20240414164347_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("RazorPages.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "They have got my project on time with the competition with a sed highly skilled, and experienced & professional team.",
                            ImgUrl = "uploads/testi_01.png",
                            Name = "James Fernando",
                            Occupation = "Manager of Racer",
                            Title = "Wonderful Support!"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you completed.",
                            ImgUrl = "uploads/testi_02.png",
                            Name = "Jacques Philips",
                            Occupation = "Designer",
                            Title = "Awesome Services!"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The master-builder of human happines no one rejects, dislikes avoids pleasure itself, because it is very pursue pleasure.",
                            ImgUrl = "uploads/testi_03.png",
                            Name = "Venanda Mercy",
                            Occupation = "Newyork City",
                            Title = "Great & Talented Team!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
